/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    'case-studies': CaseStudy;
    posts: Post;
    categories: Category;
    authors: Author;
    testimonials: Testimonial;
    'team-members': TeamMember;
    clients: Client;
    faqs: Faq;
    media: Media;
    'newsletter-subscribers': NewsletterSubscriber;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'cta-band': CtaBand;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'cta-band': CtaBandSelect<false> | CtaBandSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout: (
    | {
        variant?: ('collage' | 'editorial' | 'photo-cards' | 'dark') | null;
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        /**
         * Wrap words in [[double brackets]] to highlight them.
         */
        heading: string;
        lead?: string | null;
        /**
         * Rotated labels next to the heading, e.g. “Est. 20XX”.
         */
        stickers?:
          | {
              text: string;
              tone?: ('sun' | 'coral' | 'teal' | 'ink') | null;
              id?: string | null;
            }[]
          | null;
        ctas?:
          | {
              label: string;
              href: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Collage / photo-card images. The first one is the main image on editorial heroes.
         */
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Show email and phone from Site Settings under the lead text.
         */
        showContact?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        /**
         * One big paragraph. Wrap phrases in [[double brackets]] to emphasise.
         */
        text: string;
        cta: {
          label: string;
          /**
           * Internal path (e.g. /contact) or full URL (https://…).
           */
          href: string;
          /**
           * Open in a new tab (external links).
           */
          newTab?: boolean | null;
        };
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statement';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              value: number;
              /**
               * e.g. + or %
               */
              suffix?: string | null;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        heading?: string | null;
        statement?: string | null;
        cta: {
          label: string;
          /**
           * Internal path (e.g. /contact) or full URL (https://…).
           */
          href: string;
          /**
           * Open in a new tab (external links).
           */
          newTab?: boolean | null;
        };
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoTicker';
      }
    | {
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        heading?: string | null;
        cta: {
          label: string;
          /**
           * Internal path (e.g. /contact) or full URL (https://…).
           */
          href: string;
          /**
           * Open in a new tab (external links).
           */
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'proofTicker';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading: string;
        intro?: string | null;
        /**
         * Leave empty to show all services in their order.
         */
        services?: (number | Service)[] | null;
        layout?: ('cards' | 'accordion') | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceGrid';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading: string;
        intro?: string | null;
        /**
         * Leave empty to show the latest.
         */
        items?: (number | CaseStudy)[] | null;
        limit?: number | null;
        layout?: ('grid' | 'carousel') | null;
        cta: {
          label: string;
          /**
           * Internal path (e.g. /contact) or full URL (https://…).
           */
          href: string;
          /**
           * Open in a new tab (external links).
           */
          newTab?: boolean | null;
        };
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'workGrid';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        /**
         * Leave empty to show featured testimonials.
         */
        items?: (number | Testimonial)[] | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonialCarousel';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        subheading?: string | null;
        items?:
          | {
              label: string;
              /**
               * Where this need leads. Also pre-fills the brief builder.
               */
              service?: (number | null) | Service;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'needPicker';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'capabilities';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        steps?:
          | {
              title: string;
              subtitle?: string | null;
              body: string;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'approachSteps';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        image?: (number | null) | Media;
        items?:
          | {
              title: string;
              body: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureList';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        scope?: ('home' | 'services' | 'contact' | 'custom') | null;
        items?: (number | Faq)[] | null;
        image?: (number | null) | Media;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * Leave empty to show everyone.
         */
        members?: (number | TeamMember)[] | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamGrid';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        limit?: number | null;
        category?: (number | null) | Category;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogCarousel';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading: string;
        intro?: string | null;
        /**
         * Forms are managed under Inbox → Forms.
         */
        form: number | Form;
        layout?: ('split' | 'stacked') | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'leadForm';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        items?:
          | {
              name: string;
              bestFor: string;
              length?: string | null;
              includes?:
                | {
                    item: string;
                    id?: string | null;
                  }[]
                | null;
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'engagementModels';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading?: string | null;
        usLabel?: string | null;
        themLabel?: string | null;
        rows?:
          | {
              label: string;
              us: string;
              them: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'comparison';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        heading: string;
        steps?:
          | {
              title: string;
              body: string;
              link: {
                label: string;
                /**
                 * Internal path (e.g. /contact) or full URL (https://…).
                 */
                href: string;
                /**
                 * Open in a new tab (external links).
                 */
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'processSteps';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        buttonLabel?: string | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsletter';
      }
    | {
        /**
         * Small label above the heading, e.g. “Services”. The number is added automatically.
         */
        eyebrow?: string | null;
        columns?:
          | {
              heading: string;
              body: string;
              link: {
                label: string;
                /**
                 * Internal path (e.g. /contact) or full URL (https://…).
                 */
                href: string;
                /**
                 * Open in a new tab (external links).
                 */
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textColumns';
      }
    | {
        media: number | Media;
        /**
         * For videos.
         */
        poster?: (number | null) | Media;
        caption?: string | null;
        aspect?: ('16/9' | '4/3' | '1/1' | '21/9') | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'media';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('narrow' | 'default') | null;
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading: string;
        text?: string | null;
        link: {
          label: string;
          /**
           * Internal path (e.g. /contact) or full URL (https://…).
           */
          href: string;
          /**
           * Open in a new tab (external links).
           */
          newTab?: boolean | null;
        };
        /**
         * Background band colour.
         */
        tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Lower-case letters, numbers and dashes only.
   */
  slug: string;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  /**
   * Show the global “Ready to move forward?” band above the footer.
   */
  showCtaBand?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images, logos and videos used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Use a short empty description like “decorative” only for purely decorative images.
   */
  alt: string;
  /**
   * Generated on upload; used for blur-up placeholders.
   */
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  blurb: string;
  cardImage?: (number | null) | Media;
  /**
   * e.g. “Branding agency in Ahmedabad”.
   */
  eyebrow?: string | null;
  /**
   * Page H1. Wrap words in [[double brackets]] to highlight.
   */
  heading: string;
  lead?: string | null;
  /**
   * Pills under the heading, e.g. Brand strategy · Identity.
   */
  subServices?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * e.g. “We build brands to perform”.
   */
  checklistHeading?: string | null;
  checklistIntro?: string | null;
  checklist?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Inline consultation form shown in the hero.
   */
  form?: (number | null) | Form;
  /**
   * Extra sections below the checklist.
   */
  body?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'default') | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media: number | Media;
            /**
             * For videos.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            aspect?: ('16/9' | '4/3' | '1/1' | '21/9') | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  value: number;
                  /**
                   * e.g. + or %
                   */
                  suffix?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            image?: (number | null) | Media;
            items?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureList';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            columns?:
              | {
                  heading: string;
                  body: string;
                  link: {
                    label: string;
                    /**
                     * Internal path (e.g. /contact) or full URL (https://…).
                     */
                    href: string;
                    /**
                     * Open in a new tab (external links).
                     */
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textColumns';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Leave empty to show featured testimonials.
             */
            items?: (number | Testimonial)[] | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialCarousel';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            scope?: ('home' | 'services' | 'contact' | 'custom') | null;
            items?: (number | Faq)[] | null;
            image?: (number | null) | Media;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            /**
             * Forms are managed under Inbox → Forms.
             */
            form: number | Form;
            layout?: ('split' | 'stacked') | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadForm';
          }
        | {
            heading: string;
            text?: string | null;
            link: {
              label: string;
              /**
               * Internal path (e.g. /contact) or full URL (https://…).
               */
              href: string;
              /**
               * Open in a new tab (external links).
               */
              newTab?: boolean | null;
            };
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  /**
   * Leave empty to show case studies tagged with this service.
   */
  relatedWork?: (number | CaseStudy)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Lower-case letters, numbers and dashes only.
   */
  slug: string;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  order?: number | null;
  icon?: ('brand' | 'design' | 'growth' | 'social' | 'ai' | 'consulting') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  logo?: (number | null) | Media;
  /**
   * Shown on this service's page.
   */
  service?: (number | null) | Service;
  /**
   * Featured quotes appear in the Home carousel.
   */
  featured?: boolean | null;
  order?: number | null;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions for the FAQ accordions. Scope decides where each one appears.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  scope?: ('home' | 'services' | 'contact')[] | null;
  /**
   * Also show on this specific service page.
   */
  service?: (number | null) | Service;
  order?: number | null;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Usually the client name.
   */
  title: string;
  client: string;
  industry?: string | null;
  services: (number | Service)[];
  /**
   * Card blurb, 1–2 sentences.
   */
  summary: string;
  cover?: (number | null) | Media;
  /**
   * Headline results, e.g. 400% / Organic traffic increase.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opening paragraph under the title.
   */
  intro?: string | null;
  /**
   * The brief. Wrap phrases in [[double brackets]] to emphasise.
   */
  objective?: string | null;
  sections?:
    | {
        eyebrow?: string | null;
        heading: string;
        body: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional before/after image slider.
   */
  beforeAfter?: {
    before?: (number | null) | Media;
    after?: (number | null) | Media;
    caption?: string | null;
  };
  /**
   * Outcome timeline, e.g. Week 0 → Launch → +90 days.
   */
  timeline?:
    | {
        when: string;
        what: string;
        id?: string | null;
      }[]
    | null;
  video?: {
    /**
     * MP4/WebM upload.
     */
    file?: (number | null) | Media;
    /**
     * Or a YouTube/Vimeo URL.
     */
    url?: string | null;
    poster?: (number | null) | Media;
  };
  testimonial?: (number | null) | Testimonial;
  /**
   * Extra sections.
   */
  body?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'default') | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media: number | Media;
            /**
             * For videos.
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            aspect?: ('16/9' | '4/3' | '1/1' | '21/9') | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  value: number;
                  /**
                   * e.g. + or %
                   */
                  suffix?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            image?: (number | null) | Media;
            items?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureList';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            columns?:
              | {
                  heading: string;
                  body: string;
                  link: {
                    label: string;
                    /**
                     * Internal path (e.g. /contact) or full URL (https://…).
                     */
                    href: string;
                    /**
                     * Open in a new tab (external links).
                     */
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textColumns';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Leave empty to show featured testimonials.
             */
            items?: (number | Testimonial)[] | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialCarousel';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading?: string | null;
            scope?: ('home' | 'services' | 'contact' | 'custom') | null;
            items?: (number | Faq)[] | null;
            image?: (number | null) | Media;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Small label above the heading, e.g. “Services”. The number is added automatically.
             */
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            /**
             * Forms are managed under Inbox → Forms.
             */
            form: number | Form;
            layout?: ('split' | 'stacked') | null;
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadForm';
          }
        | {
            heading: string;
            text?: string | null;
            link: {
              label: string;
              /**
               * Internal path (e.g. /contact) or full URL (https://…).
               */
              href: string;
              /**
               * Open in a new tab (external links).
               */
              newTab?: boolean | null;
            };
            /**
             * Background band colour.
             */
            tone?: ('paper' | 'paper-2' | 'white' | 'teal-ink' | 'teal') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Lower-case letters, numbers and dashes only.
   */
  slug: string;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  publishedAt?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  socials?:
    | {
        platform: 'LinkedIn' | 'Instagram' | 'X' | 'Website';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Founders get the spotlight block on Culture.
   */
  founder?: boolean | null;
  order?: number | null;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  /**
   * URL path segment. Lower-case letters, numbers and dashes only.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown on cards and as the dek under the title.
   */
  excerpt: string;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Lower-case letters, numbers and dashes only.
   */
  slug: string;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  category: number | Category;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | Author;
  publishedAt?: string | null;
  /**
   * Leave empty to pick by category.
   */
  related?: (number | Post)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos for the client marquee. Lower order = earlier in the ticker.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * SVG preferred. Mono/dark version; it is tinted on dark bands.
   */
  logo?: (number | null) | Media;
  website?: string | null;
  featured?: boolean | null;
  order?: number | null;
  /**
   * Tick while this is placeholder copy or imagery. Untick once real content is in.
   */
  placeholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who subscribed to The Upshot. Export as CSV for your email tool.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Page the form was submitted from.
   */
  source?: string | null;
  confirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              lead?: T;
              stickers?:
                | T
                | {
                    text?: T;
                    tone?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              showContact?: T;
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              eyebrow?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        logoTicker?:
          | T
          | {
              heading?: T;
              statement?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        proofTicker?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              heading?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              services?: T;
              layout?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        workGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?: T;
              limit?: T;
              layout?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        testimonialCarousel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        needPicker?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    label?: T;
                    service?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        capabilities?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        approachSteps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    body?: T;
                    image?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              image?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              scope?: T;
              items?: T;
              image?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              members?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        blogCarousel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              limit?: T;
              category?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        leadForm?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              form?: T;
              layout?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        engagementModels?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    name?: T;
                    bestFor?: T;
                    length?: T;
                    includes?:
                      | T
                      | {
                          item?: T;
                          id?: T;
                        };
                    highlight?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              usLabel?: T;
              themLabel?: T;
              rows?:
                | T
                | {
                    label?: T;
                    us?: T;
                    them?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    body?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              buttonLabel?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        textColumns?:
          | T
          | {
              eyebrow?: T;
              columns?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              poster?: T;
              caption?: T;
              aspect?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  placeholder?: T;
  showCtaBand?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  blurb?: T;
  cardImage?: T;
  eyebrow?: T;
  heading?: T;
  lead?: T;
  subServices?:
    | T
    | {
        label?: T;
        id?: T;
      };
  heroImage?: T;
  checklistHeading?: T;
  checklistIntro?: T;
  checklist?:
    | T
    | {
        item?: T;
        id?: T;
      };
  form?: T;
  body?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              poster?: T;
              caption?: T;
              aspect?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              image?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        textColumns?:
          | T
          | {
              eyebrow?: T;
              columns?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        testimonialCarousel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              scope?: T;
              items?: T;
              image?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        leadForm?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              form?: T;
              layout?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedWork?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  placeholder?: T;
  order?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  industry?: T;
  services?: T;
  summary?: T;
  cover?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  intro?: T;
  objective?: T;
  sections?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
        caption?: T;
      };
  timeline?:
    | T
    | {
        when?: T;
        what?: T;
        id?: T;
      };
  video?:
    | T
    | {
        file?: T;
        url?: T;
        poster?: T;
      };
  testimonial?: T;
  body?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              poster?: T;
              caption?: T;
              aspect?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              image?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        textColumns?:
          | T
          | {
              eyebrow?: T;
              columns?:
                | T
                | {
                    heading?: T;
                    body?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        testimonialCarousel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              scope?: T;
              items?: T;
              image?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        leadForm?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              form?: T;
              layout?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    newTab?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  placeholder?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  placeholder?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  related?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  avatar?: T;
  logo?: T;
  service?: T;
  featured?: T;
  order?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  founder?: T;
  order?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  featured?: T;
  order?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  service?: T;
  order?: T;
  placeholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  confirmed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, socials and defaults used everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline?: string | null;
  email: string;
  /**
   * [PLACEHOLDER] until the real number is supplied.
   */
  phone?: string | null;
  /**
   * tel: link, digits only e.g. +919876543210
   */
  phoneHref?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  hours?: string | null;
  mapUrl?: string | null;
  socials?:
    | {
        platform: 'Instagram' | 'LinkedIn' | 'X' | 'YouTube' | 'Behance' | 'Dribbble';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Headline numbers reused across the site.
   */
  stats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Trust badges shown as stickers in heroes, e.g. “Est. 20XX”.
   */
  badges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  /**
   * Reserved for later. Leave empty.
   */
  analyticsId?: string | null;
  legalName?: string | null;
  /**
   * e.g. GSTIN / CIN. [PLACEHOLDER]
   */
  registrationNumbers?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Main navigation. Items with children become dropdown menus.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        /**
         * Dropdown entries.
         */
        children?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    href: string;
  };
  secondary?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Short agency description at the top of the footer.
   */
  description?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    text?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
  };
  legal?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-band".
 */
export interface CtaBand {
  id: number;
  /**
   * Optional emoji above the heading.
   */
  emoji?: string | null;
  heading: string;
  subheading?: string | null;
  link: {
    label: string;
    /**
     * Internal path (e.g. /contact) or full URL (https://…).
     */
    href: string;
    /**
     * Open in a new tab (external links).
     */
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  phoneHref?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  hours?: T;
  mapUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  badges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  defaultTitle?: T;
  defaultDescription?: T;
  defaultImage?: T;
  analyticsId?: T;
  legalName?: T;
  registrationNumbers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        text?: T;
        placeholder?: T;
        buttonLabel?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-band_select".
 */
export interface CtaBandSelect<T extends boolean = true> {
  emoji?: T;
  heading?: T;
  subheading?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}